openapi: 3.0.0
info:
  description: This API provides consistency checks between the database and the Kafka queue
  version: "1.0.0"
  title: Consistency API
  contact:
    email: student@bcit.ca

paths:
  /consistency_check/update:
    post:
      summary: Perform a consistency check and update the results.
      operationId: app.update_consistency_check
      description: |
        This endpoint triggers a consistency check by:
        - Fetching event counts and IDs from the processing, analyzer, and storage services.
        - Comparing the `trace_id` lists from the analyzer and storage services.
        - Identifying:
          - Events that are in the queue but not in the database.
          - Events that are in the database but not in the queue.
        - Saving the results to a JSON file.
        Returns the total time (in milliseconds) taken to perform the consistency check.
      responses:
        '200':
          description: Consistency check completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  processing_time_ms:
                    type: integer                    
        
  /consistency_check/checks:
    get:
      summary: Displays the results of the checks
      operationId: app.get_checks
      description: |
        This endpoint retrieves the results of the most recent consistency check from the JSON file.
        If no consistency checks have been run yet, it returns a 404 error.
      responses:
        '200':
          description: Latest consistency check results retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checks'
                type: object
                properties:
                  last_updated:
                    type: string
                    format: date-time
                    description: The timestamp of the last consistency check.
                    example: "2025-03-15T14:30:00Z"
                  counts:
                    type: object
                    properties:
                      db:
                        type: object
                        description: Event counts from the database.
                        example:
                          event1: 10
                          event2: 5
                      queue:
                        type: object
                        description: Event counts from the queue.
                        example:
                          event1: 7
                          event2: 3
                      processing:
                        type: object
                        description: Event counts from the processing service.
                        example:
                          event1: 2
                          event2: 8
                  missing_in_db:
                    type: array
                    description: Events present in the queue but missing from the database.
                    items:
                      type: object
                      properties:
                        event_id:
                          type: integer
                          description: The unique event ID.
                          example: 12345
                        trace_id:
                          type: string
                          description: The unique trace ID associated with the event.
                          example: "550e8400-e29b-41d4-a716-446655440000"
                        type:
                          type: string
                          description: The type of event.
                          example: "snow"
                  missing_in_queue:
                    type: array
                    description: Events present in the database but missing from the queue.
                    items:
                      type: object
                      properties:
                        event_id:
                          type: integer
                          description: The unique event ID.
                          example: 67890
                        trace_id:
                          type: string
                          description: The unique trace ID associated with the event.
                          example: "8f14e45f-e26c-48d3-a716-5579bbd4ed2a"
                        type:
                          type: string
                          description: The type of event.
                          example: "lift"
        '404':
          description: No consistency checks have been run yet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        
components:
  schemas:
    Checks:
      required:
      - counts
      - not_in_db
      - not_in_queue
      - last_updated
      type: object
      properties:
        last_updated:
          type: string
          format: date-time
        counts:
          type: object
          properties:
            db:
              type: object
              properties:
                event1:
                  type: integer
                event2:
                  type: integer
            queue:
              type: object
              properties:
                event1:
                  type: integer
                event2:
                  type: integer
            processing:
              type: object
              properties:
                event1:
                  type: integer
                event2:
                  type: integer
        not_in_db:
          type: array
          items:
            type: object
            properties:
              event_id:
                type: integer
              trace_id:
                type: integer
        not_in_queue:
          type: array
          items:
            type: object
            properties:
              event_id:
                type: integer
              trace_id:
                type: integer